/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kesehatan;

import java.util.ArrayList;
import kesehatan.Poliklinik;
import javax.swing.*;
/**
 *
 * @author taiba
 */
public class framePoliklinik extends javax.swing.JFrame {

    /**
     * Creates new form FramePoliklinik
     */
    public framePoliklinik() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        KodePoli = new javax.swing.JLabel();
        btnKodePoli = new javax.swing.JTextField();
        NamaPoliklinik = new javax.swing.JLabel();
        btnNamaPoliklinik = new javax.swing.JTextField();
        btnProses = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        KodePoli.setText("Kode Poli");

        btnKodePoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKodePoliActionPerformed(evt);
            }
        });

        NamaPoliklinik.setText("Nama Poliklinik");

        btnProses.setText("Proses");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(KodePoli)
                            .addComponent(NamaPoliklinik))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnKodePoli, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(btnNamaPoliklinik)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnKembali)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnProses)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KodePoli)
                    .addComponent(btnKodePoli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NamaPoliklinik)
                    .addComponent(btnNamaPoliklinik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProses)
                    .addComponent(btnKembali))
                .addContainerGap(166, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKodePoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKodePoliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKodePoliActionPerformed

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
    String kode = btnKodePoli.getText();
    String nama = btnNamaPoliklinik.getText();
    
    Poliklinik poli = new Poliklinik(kode, nama);
    
     javax.swing.JOptionPane.showMessageDialog(this,
        "Data berhasil diproses:\n" +
        "Kode Poli: " + poli.getKodePoli() + "\n" +
        "Nama Poliklinik: " + poli.getNamaPoliklinik(),
        "Informasi",
        javax.swing.JOptionPane.INFORMATION_MESSAGE
    );


    }//GEN-LAST:event_btnProsesActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new framePoliklinik().setVisible(true); // << ini penting!
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel KodePoli;
    private javax.swing.JLabel NamaPoliklinik;
    private javax.swing.JButton btnKembali;
    private javax.swing.JTextField btnKodePoli;
    private javax.swing.JTextField btnNamaPoliklinik;
    private javax.swing.JButton btnProses;
    // End of variables declaration//GEN-END:variables
}
